version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=easy_storage
      - STORAGE_TYPE=s3
      - STORAGE_ENDPOINT=minio
      - STORAGE_REGION=us-east-1
      - STORAGE_BUCKET=easy-storage
      - STORAGE_ACCESS_KEY=minio
      - STORAGE_SECRET_KEY=minio123
      - STORAGE_FORCE_PATH_STYLE=true
      - JWT_SECRET=your-secret-key

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=easy_storage
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data: